app/blog/urls.py
'''
Urls
'''

from django.urls import path
from .views import *

urlpatterns = [
    path('blog/', blog, name="blog"),
    path('post/crear', crear_post, name="crear_post"),
    path('post/eliminar/<int:post_id>', eliminar_post, name="eliminar_post"),
]

app/carrito/urls.py
from django.urls import path
from .views import *


app_name = "cart"

urlpatterns = [
    path('agregarproducto/<int:producto_id>', add_product, name="add_product"),
    path('removerproducto/<int:producto_id>', remove_product, name="remove_product"),
    path('decrementarproducto/<int:producto_id>', decrement_product, name="decrement_product"),
    path('limpiarcarrito', clear_cart, name="clear_cart"),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls")),
    path('autenticacion/', include("autenticacion.urls")),
    path('', include("productos.urls")),
    path('carrito/', include("carrito.urls")),
    path('pedidos/', include("pedidos.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/carrito/models.py
from django.db import models

# Create your models here.

app/carrito/views.py
from django.shortcuts import redirect
from productos.models import Productos
from django.contrib.auth.decorators import login_required
from .carrito import Carrito


@login_required(login_url="/autenticacion/acceder")
def add_product(request, producto_id):
    carrito = Carrito(request)
    producto = Productos.objects.get(id=producto_id)
    carrito.add(producto=producto)
    return redirect("list_products")


@login_required(login_url="/autenticacion/acceder")
def remove_product(request, producto_id):
    carrito = Carrito(request)
    producto = Productos.objects.get(id=producto_id)
    carrito.remove(producto=producto)
    return redirect("list_products")


@login_required(login_url="/autenticacion/acceder")
def decrement_product(request, producto_id):
    carrito = Carrito(request)
    producto = Productos.objects.get(id=producto_id)
    carrito.decrement(producto=producto)
    return redirect("list_products")


@login_required(login_url="/autenticacion/acceder")
def clear_cart(request):
    carrito = Carrito(request)
    carrito.clear()
    return redirect("list_products")

app/templates/carrito/widget.html
{% load carrito_tags %}
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
<div class="card bg-primary" style="max-width: 18rem;">
    <div class="card-header text-white text-center">
        Carrito de compras
    </div>
    {% if request.session.carrito.items %}
        {% for key, value in request.session.carrito.items %}
            <div class="card p-3">
                <ul class="list-group list-group-flush">
                    <li class="card-body text-primary list-group-item">Producto: {{ value.nombre }}</li>
                </ul>
                <div class="card-body p-0">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Precio: {{ value.precio|money_format:"$" }}</li>
                        <li class="list-group-item">Cantidad: {{ value.cantidad }}</li>
                    </ul>
                </div>
                <div class="flex-row">
                    <a class="align-left text-center">Subtotal: {{ value.precio|multiply:value.cantidad|money_format:"$" }}</a>
                    <a class="btn btn-success" href="{% url 'cart:add_product' value.producto_id %}" class="btn-sm btn btn-success">+</a>
                    <a class="btn btn-danger remove_red_eye" href="{% url 'cart:decrement_product' value.producto_id %}" class="btn-sm btn btn-danger">-</a>
                </div>
            </div>

        {% endfor %}
     {% else %}
        <div class="card-footer alert alert-danger text-center">
            No tienes productos en el carrito
        </div>
    {% endif %}
        <div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Total: {{ cart_total_amount|money_format:"$" }}</li>
                {% if request.session.carrito.items  %}
                    <a href="{% url "procesar_pedido" %}" class="btn btn-success">Crear pedido</a>
                {% endif %}
            </ul>
        </div>
    </div>